apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo-logs

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway-v1
  labels:
    app: service-gateway
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-gateway
      version: v1
  template:
    metadata:
      labels:
        app: service-gateway
        version: v1
    spec:
      containers:
        - name: service-gateway
          image: qkdrmsgh73/service-gateway:6
          ports:
            - containerPort: 8762
          resources: {}
          env:
            - name: USE_PROFILE
              value: dev
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8762
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8762
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - mountPath: /logs
              name: pvc-volume
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-share-storage
