apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-gateway
  template:
    metadata:
      labels:
        app: service-gateway
    spec:
      containers:
        - name: service-gateway
          image: qkdrmsgh73/service-gateway:6
          ports:
            - containerPort: 8762
          resources: {}
          env:
            - name: USE_PROFILE
              value: dev
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8762
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8762
            initialDelaySeconds: 60
            periodSeconds: 10
          volumeMounts:
            - mountPath: /logs
              name: pvc-volume
      nodeSelector:
        disktype: ssd
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-share-storage
