apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway-v1
  labels:
    app: service-gateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-gateway
      version: v1
  template:
    metadata:
      labels:
        app: service-gateway
        version: v1
    spec:
      containers:
        - name: service-gateway
          image: qkdrmsgh73/service-gateway
          ports:
            - containerPort: 8762
          resources: {}
          env:
            - name: USE_PROFILE
              value: dev