apiVersion: v1
kind: Service
metadata:
  name: service-gateway
  labels:
    app: service-gateway
    service: service-gateway
spec:
  ports:
    - port: 8762
      targetPort: 8762
      name: http
  selector:
    app: service-gateway