apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  selector:
    matchLabels:
      app: config-service
  replicas: 2
  template:
    metadata:
      labels:
        app: config-service
    spec:
#      imagePullSecrets:
#        - name: {k8s 내에서 생성한 secret 명, dockerhub 내 private repository에 접근하기 위함.}
      containers:
        - name: my-app
          image: qkdrmsgh73/service-config:{Jenkins build number}
          ports:
              - containerPort: 8670