apiVersion: v1
kind: Service
metadata:
  name: service-config
  labels:
    app: cservice-config
spec:
  type: LoadBalancer
  selector:
    app: service-config
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8670