apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    service: grafana
spec:
  ports:
    - port: 3001
      targetPort: 3000
      name: http
  selector:
    app: grafana