apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-v1
  labels:
    app: rabbitmq
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      version: v1
  template:
    metadata:
      labels:
        app: rabbitmq
        version: v1
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: sweep
            - name: RABBITMQ_DEFAULT_PASS
              value: sweep