apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-v1
  labels:
    app: zookeeper
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      version: v1
  template:
    metadata:
      labels:
        app: zookeeper
        version: v1
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"