apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-survey-v1
  labels:
    app: service-survey
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-survey
      version: v1
  template:
    metadata:
      labels:
        app: service-survey
        version: v1
    spec:
      containers:
        - name: service-survey
          image: qkdrmsgh73/service-survey:10
          ports:
            - containerPort: 7503
          resources: {}
          env:
            - name: USE_PROFILE
              value: local
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 2222
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 2222
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - mountPath: /logs
              name: pvc-volume
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-share-storage