kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-ui-deployment
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka
          image: provectuslabs/kafka-ui
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value : "kubernetnes"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: INTERNAL://kafka-service:29092,INTERNAL://kafka-service-1:29093,INTERNAL://kafka-service-2:29094
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: "zookeeper:2181"
