apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: my_channel

apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  labels:
    app: service-discovery
    service: service-discovery
spec:
  ports:
    - port: 8761
      targetPort: 8761
      name: http
  selector:
    app: service-discovery
