apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  labels:
    app: service-discovery
    service: service-discovery
spec:
  ports:
    - port: 8761
      targetPort: 8761
      name: http
  selector:
    app: service-discovery