apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth-v1
  labels:
    app: service-auth
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-auth
      version: v1
  template:
    metadata:
      labels:
        app: service-auth
        version: v1
    spec:
      nodeSelector:
        disktype: ssd
      containers:
        - name: service-auth
          image: qkdrmsgh73/service-auth:31
          ports:
            - containerPort: 7500
          resources: {}
          env:
            - name: USE_PROFILE
              value: local
            - name: REDIS_PORT
              value: "6379"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 2222
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 2222
            initialDelaySeconds: 60
            periodSeconds: 10
          volumeMounts:
            - mountPath: /logs
              name: pvc-volume
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-share-storage