apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth-v1
  labels:
    app: service-auth
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-auth
      version: v1
  template:
    metadata:
      labels:
        app: service-auth
        version: v1
    spec:
      containers:
        - name: service-auth
          image: qkdrmsgh73/service-auth:8
          ports:
            - containerPort: 7500
          resources: {}
          env:
            - name: USE_PROFILE
              value: dev
            - name: REDIS_PORT
              value: "6379"