apiVersion: v1
kind: Service
metadata:
  name: service-auth
  labels:
    app: service-auth
    service: service-auth
spec:
  ports:
    - port: 7500
      targetPort: 2222
      name: http
  selector:
    app: service-auth