apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-zipkin-v1
  labels:
    app: service-zipkin
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-zipkin
      version: v1
  template:
    metadata:
      labels:
        app: service-zipkin
        version: v1
    spec:
      containers:
        - name: service-zipkin
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411
          resources: {}
