apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
    service: zipkin
spec:
  ports:
    - port: 9411
      targetPort: 9411
      name: http
  selector:
    app: service-zipkin