apiVersion: v1
kind: Service
metadata:
  name: kafka-service-2
spec:
  selector:
    app: kafka-service-2
  ports:
    - name : external
      protocol: TCP
      port: 9094
      targetPort: 9094
    - name : internal
      protocol: TCP
      port: 29094
      targetPort: 29094