apiVersion: v1
kind: Service
metadata:
  name: kafka-service-2
spec:
  selector:
    app: kafka-service-2
  ports:
    - name : external
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name : internal
      protocol: TCP
      port: 29092
      targetPort: 29092