##################################################################################################
# FileBeat
##################################################################################################

apiVersion: v1
kind: Service
metadata:
  name: filebeat
  labels:
    app: filebeat
    service: filebeat
spec:
  ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
  selector:
    app: filebeat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-1
  labels:
    app: filebeat-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat-1
  template:
    metadata:
      labels:
        app: filebeat-1
    spec:
      containers:
      - args:
          - filebeat
          - -e
          - -strict.perms=false
        name: filebeat-1
        image: docker.elastic.co/beats/filebeat:7.13.0
        ports:
        - containerPort: 9999
        volumeMounts:
          - mountPath: /usr/share/filebeat
            name: pvc-volume
            readOnly: true
#          - mountPath: /usr/share/filebeat/logs
#            name: pvc-volume2
#            readOnly: true
      restartPolicy: Always
      volumes:
      - name: pvc-volume
        nfs:
          server: 172.16.0.114
          path: /sweep/filebeat/config
#      - name: pvc-volume2
#        nfs:
#          server: 172.16.0.114
#          path: /sweep/service_logs
