##################################################################################################
# Kibana
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
    service: kibana
spec:
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-v1
  labels:
    app: kibana
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      version: v1
  template:
    metadata:
      labels:
        app: kibana
        version: v1
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.13.0
          volumeMounts:
          - mountPath: ./kibana/config
            name: pvc-volume
          ports:
            - containerPort: 5601
      restartPolicy: Always
      volumes:
      - name: pvc-volume
        nfs:
          server: 172.16.0.114
          path: /sweep/kibana

