##################################################################################################
# LogStash
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
    service: logstash
spec:
  ports:
    - name: "5044"
      port: 5044
      targetPort: 5044
    - name: "5000"
      port: 5000
      targetPort: 5000
    - name: "5000-udp"
      port: 5000
      protocol: UDP
      targetPort: 5000
    - name: "9600"
      port: 9600
      targetPort: 9600
  selector:
    app: logstash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-v1
  labels:
    app: logstash
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
      version: v1
  template:
    metadata:
      labels:
        app: logstash
        version: v1
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.13.0
          volumeMounts:
          - mountPath: ./logstash/config
            name: pvc-volume
          - mountPath: ./logstash/pipeline
            name: pvc-volume2
          ports:
            - containerPort: 5044
            - containerPort: 5000
            - containerPort: 5000
              protocol: UDP
            - containerPort: 9600
          env:
              - name: LS_JAVA_OPTS
                value: -Xmx256m -Xms256m
      restartPolicy: Always
      volumes:
      - name: pvc-volume
        nfs:
          server: 172.16.0.114
          path: /sweep/logstash
      - name: pvc-volume2
        nfs:
          server: 172.16.0.114
          path: /sweep/logstash/pipeline

