kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-rest-proxy
          image: confluentinc/cp-kafka-rest:6.2.1
          ports:
            - containerPort: 8082
          env:
            - name: KAFKA_REST_LISTENERS
              value: http://0.0.0.0:8082/
            - name: KAFKA_REST_SCHEMA_REGISTRY_URL
              value: 'zookeeper-service:2181'
            - name: KAFKA_REST_HOST_NAME
              value: kafka-rest-proxy
            - name:  KAFKA_REST_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka:29092