apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    service: kafka
spec:
  ports:
    - name: external
      port: 9092
      targetPort: 9092
    - name: internal
      port: 29092
      targetPort: 29092
  selector:
    app: kafka