apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-response-v1
  labels:
    app: service-response
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-response
      version: v1
  template:
    metadata:
      labels:
        app: service-response
        version: v1
    spec:
      containers:
        - name: service-response
          image: qkdrmsgh73/service-response
          ports:
            - containerPort: 7502
          resources: {}
          env:
            - name: USE_PROFILE
              value: dev