apiVersion: v1
kind: Service
metadata:
  name: service-response
  labels:
    app: service-response
    service: service-response
spec:
  ports:
    - port: 7502
      targetPort: 2222
      name: http
  selector:
    app: service-response