apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-front
  template:
    metadata:
      labels:
        app: service-front
    spec:
      containers:
        - name: service-gateway
          image: qkdrmsgh73/service-front:80
          ports:
            - containerPort: 3000
          resources: {}
      nodeSelector:
        disktype: ssd