apiVersion: v1
kind: Service
metadata:
  name: service-front
  labels:
    app: service-front
    service: service-front
spec:
  type: LoadBalancer
  ports:
    - port: 8762
      targetPort: 8762
  selector:
    app: service-front