apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-config
spec:
  selector:
    matchLabels:
      app: service-config
  replicas: 1
  template:
    metadata:
      labels:
        app: service-config
    spec:
#      imagePullSecrets:
#        - name: {k8s 내에서 생성한 secret 명, dockerhub 내 private repository에 접근하기 위함.}
      containers:
        - name: config-service
          image: qkdrmsgh73/service-config:latest
          ports:
              - containerPort: 8760