apiVersion: v1
kind: Service
metadata:
  name: service-config
  labels:
    app: service-config
    service: service-config
spec:
  type: LoadBalancer
  ports:
    - port: 8760
      targetPort: 8760
      name: http
  selector:
    app: service-config