apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-v1
  labels:
    app: redis
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      version: v1
  template:
    metadata:
      labels:
        app: redis
        version: v1
    spec:
      containers:
        - name: redis
          image: redis
          command:
            - "redis-server"
          args:
            - "--port"
            - "6379"
          ports:
            - containerPort: 6379
          resources: {}